language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

sudo: true

env:
  global:
    - TEST_COMMAND="composer test"
    - AMP_DEBUG=true

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true
  include:
    - php: 7.0
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
    - php: 7.2
      env: COVERAGE=true TEST_COMMAND="composer test-coverage"
    - php: 7.2
      env: TEST_COMMAND="composer lint"

before_install:
  - phpenv config-rm xdebug.ini || echo "No xdebug config."
  - sudo add-apt-repository ppa:ondrej/php -y
  - sudo apt-get -qq update
  - sudo apt-get install -y libsodium-dev
  - pecl install libsodium

install:
  - travis_retry composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction
  - if [[ $COVERAGE = true ]]; then wget https://github.com/php-coveralls/php-coveralls/releases/download/v1.0.2/coveralls.phar; fi
  - if [[ $COVERAGE = true ]]; then chmod +x coveralls.phar; fi

script:
  - composer validate --strict --no-check-lock
  - $TEST_COMMAND

after_script:
  - if [[ $COVERAGE = true ]]; then ./coveralls.phar -v; fi